name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da Aplicação
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: oig04/hello-app:${{ github.sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório de Manifestos
        uses: actions/checkout@v3
        with:
          repository: oig04/projeto-ci-cd-gh-actions-manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: main

      - name: Atualizar a tag da imagem no Deployment
        run: |
          sed -i 's|\(image: oig04/hello-app:\).*|\1${{ github.sha }}|' deployment.yaml

      - name: Commit e Push da alteração
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add deployment.yaml
          git commit -m "CI: Atualizando imagem para a versão ${{ github.sha }}"
          git push
